dist: trusty
sudo: required
language: node_js
node_js:
- '7'

addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run
  deploy
env:
  global:
  - secure: xAmB74IXZ+1uiyFvaApsptIwmHQDrAmVVZ8FhS2av7VGtNEzlbN+1kXbPJ02HbfgL9hmhpMOr7Upw10Wu0Is6qZj0QL3TmKeU9nUxOe9vmh5ti+6EqCQo8T6HnBj1s2hl1d07gPMyFRkOpREs1WFOfOlh+Fhu5hSlD0NXhezbMUwc3fChB9W16SIn4s3bny78tmRhfeZrtRZFdFe1j0YDAk1WTPtmhr0aEOaHjDsoer1sZdPw/T56+xi4jaDmZ0ATXs3RtAQl/zSOn4uWJrdazQ5FWsAsubXxSm5tFMxIs7Jw844/4puYvK2yg1kfjcWZSAfWTW4Dvd6HvckFa/Ve1YVCXqAOvztXUMoqC77abtG7v3eM2i47lPvoe/qsvReP07rdtavqBmLhr2AboHdv8JexjUUQryrtWZDv8q2R0ZfVKsJG0OxmddWE+qirU2B3xn5PKMzcOUtD82ToB61LXKC5IOZBNMqOcXlUv63uWd9QkhDh3bkdxK8NgOJ0KxARY0vPYM9LPbinvzeRLNN0rx4D3odTQgiaGePz3VV65Bxs6D0zhXgi2q2ekiDmNfbtUK3uRjLVQ+rdwV81unnxx9YcUDTHwDgBEADltkhoIOfjy2gbsEeXNPVCOj5Q9Yz6i/R5pSJbKdiprsevn5quHNqe40DeouScmGtfof3cGM=
  - secure: MSN2SPmJ5lzLuhy+n8HI2fE1S3YMnwMq2115smJZuOZFegKzI4eE1XgiDQ8ytFfJgjmzc0ECbNnrmvPoOuQ8R35D5XmQc8wg0PADjueyuofeflcd0oSULvb1R9UKHtdFqSyq3SORz5EipRuD/F6JSVW0a28ZDfrSl7OP6InKwY8ZvAraZpcCtDIYTqggkcsbvx7hWHrvfAwn6kUsrf6Zm9OZjELwHnCilUlu7LgV904cpoAhPqfixhtr4wofY1MOHIol+9jVYcuLgug5f/qIQXrd0zJMfHtaIdOqjPcR04Iu+IoDqhOqEG38p6Wo+6ssYBU4jobz5lX5dfHCJGchpfIxrDq1FqUXdP+kG4c8KDR0Un2jZj7d73AXA3GSQttJEkgx5rTI7P68NpLptw5eL47u1emeIj8rGHrEBWkcytU+nkVP/Wagewhl1d+Wb+N7hEPCy/4dYcaK+U5jEWA9uIHM8d7O2tTCHJ+PGEZEH+p5ZzLpwWD7sG7Mkn9mfDaputKTBPxYa0DaeOAdefDMkjjlhB+rUgdoiNq8/3r8PbkG2I5QyJbB7NlcvplOmTH1RQGupLzyhr/DrmTB/9gTPD8u1OXzkOKSmGumfZ5/3lnSihNZMl+sGvVmDDMEV7X52XazcizqvDTFI3XgDCesFumPuOU50R3c25pbg+6dEK8=
