language: node_js
sudo: required
dist: trusty
node_js:
  - "node"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # wait for xvfb to start
