language: node_js
node_js:
- node
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && npm run gh-pages
env:
  global:
    secure: xAmB74IXZ+1uiyFvaApsptIwmHQDrAmVVZ8FhS2av7VGtNEzlbN+1kXbPJ02HbfgL9hmhpMOr7Upw10Wu0Is6qZj0QL3TmKeU9nUxOe9vmh5ti+6EqCQo8T6HnBj1s2hl1d07gPMyFRkOpREs1WFOfOlh+Fhu5hSlD0NXhezbMUwc3fChB9W16SIn4s3bny78tmRhfeZrtRZFdFe1j0YDAk1WTPtmhr0aEOaHjDsoer1sZdPw/T56+xi4jaDmZ0ATXs3RtAQl/zSOn4uWJrdazQ5FWsAsubXxSm5tFMxIs7Jw844/4puYvK2yg1kfjcWZSAfWTW4Dvd6HvckFa/Ve1YVCXqAOvztXUMoqC77abtG7v3eM2i47lPvoe/qsvReP07rdtavqBmLhr2AboHdv8JexjUUQryrtWZDv8q2R0ZfVKsJG0OxmddWE+qirU2B3xn5PKMzcOUtD82ToB61LXKC5IOZBNMqOcXlUv63uWd9QkhDh3bkdxK8NgOJ0KxARY0vPYM9LPbinvzeRLNN0rx4D3odTQgiaGePz3VV65Bxs6D0zhXgi2q2ekiDmNfbtUK3uRjLVQ+rdwV81unnxx9YcUDTHwDgBEADltkhoIOfjy2gbsEeXNPVCOj5Q9Yz6i/R5pSJbKdiprsevn5quHNqe40DeouScmGtfof3cGM=
